In [1]:
import pandas as pd
import numpy as np
import gc

In [2]:
def write_to_csv(p_data,p_path):
    dataframe = pd.DataFrame(p_data)
    dataframe.to_csv(p_path, mode='a',header=False,index=False,sep=',')
    del dataframe
    gc.collect()
    
def csv_read(p_path):
    p_data=np.array(pd.read_csv(p_path, sep=',', header=None))
    print('data.shape',p_data.shape)
    return p_data

In [3]:
data = pd.read_csv('../data/cheng10142021.csv')
print(data.shape) 
print(data)

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (19,21,23,25,27,40,43,45,47,50,60,62,64,66,68,70,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,133,155,164,175,178,188,216,219,221,223,225,227,229,231,233,235,237,239,241,243,245,247,249,251,253,255,257,259,261,263,265,267,269,271,381,396,398,400,418,420,422,431,444,453,493,566,574,599,635,651,665,668,671,676,688,699,705,707,792,798,800,801,984,986,988,989,991,998,1000,1002,1003,1010,1012,1014,1016,1017,1024,1039,1053,1067,1081,1083,1089,1090,1091,1092,1098,1099,1107,1118,1120,1122,1124,1130,1191,1246,1247,1248,1256,1257,1258,1259,1269,1291,1294,1297,1333,1349,1351,1353,1355,1357,1359,1361,1363,1365,1367,1369,1371,1373,1375,1377,1379,1381,1383,1385,1387,1389,1391,1393,1395,1397,1399,1401,1403,1453,1454,1456,1457,1460,1461,1464,1465,1468,1469,1472,1473,1547,1606,1615,1617,1619,1621,1632,1634,1636,1644,1646,1648,1650,1658,1660,1662,1664,1690) h

(163199, 1727)
            NACCID  NACCADC PACKET  FORMVER  VISITMO  VISITDAY  VISITYR  \
0       NACC000385      289      I      1.0       11         8     2006   
1       NACC000385      289      F      2.0        3        19     2008   
2       NACC000385      289      F      2.0        3         4     2009   
3       NACC000385      289      F      2.0        4        21     2010   
4       NACC000385      289      F      2.0        1        28     2011   
...            ...      ...    ...      ...      ...       ...      ...   
163194  NACC998475     9661      F      1.0       11        15     2007   
163195  NACC998475     9661      F      2.0       11         6     2008   
163196  NACC999391     9661      I      1.0        3         2     2006   
163197  NACC999391     9661      F      1.0        5        17     2007   
163198  NACC999391     9661      F      2.0        3        27     2008   

        NACCVNUM  NACCAVST  NACCNVST  ...  LBOTHYR  LBOTHMO  LBOTHPOS  \
0          

In [4]:
# Form header, Milestones, Other data available at NACC, and so on
DelName=['NACCADC','PACKET','FORMVER','NPFORMVER','NACCMOD', 'NACCYOD','VISITMO','VISITDAY','VISITYR','NACCVNUM','NACCNVST','NACCDAYS','NACCDIED','NACCAUTP', 'NACCACTV','NACCNOVS', 'NACCDSMO', 'NACCDSDY', 'NACCDSYR', 'NACCNURP','NACCNRMO', 'NACCNRDY','NACCNRYR','NACCMDSS','NACCPAFF','NACCFTD','NACCLBDM','NACCMRSA','NACCNAPA','NACCAPSA','NACCACSF','NACCPCSF','NACCTCSF', 'NACCAUTP']#'NACCAVST'

In [5]:
data_store=data.copy()
data_store_=data_store.drop(DelName, axis=1)
data_store_.shape

(163199, 1694)

In [6]:
data_store_arr=np.array(data_store_)
data_store_arr.shape

(163199, 1694)

In [7]:
data_store_arr

array([['NACC000385', 7, 0, ..., nan, nan, nan],
       ['NACC000385', 7, 497, ..., nan, nan, nan],
       ['NACC000385', 7, 847, ..., nan, nan, nan],
       ...,
       ['NACC999391', 3, 0, ..., nan, nan, nan],
       ['NACC999391', 3, 441, ..., nan, nan, nan],
       ['NACC999391', 3, 756, ..., nan, nan, nan]], dtype=object)

In [8]:
data_store_title=data_store_.columns.values.tolist()
data_store_title_arr=np.array(data_store_title)
print(data_store_title_arr.shape)
print(data_store_title_arr)

(1694,)
['NACCID' 'NACCAVST' 'NACCFDYS' ... 'LBOCGDY' 'LBOCGPOS' 'LBOCGAVL']


In [9]:
# LATE

#-------------------------------------------------------------------------------------------
# 1. DISTRIBUTION OF TDP-43 IMMUNOREACTIVE INCLUSIONS
# Only using 0 (No) and 1 (Yes), considering three regions: Amygdala (NPTDPB) Stage 1, Hippocampus (NPTDPC) Stage 2, Neocortex (NPTDPE) Stage 3
# On the above three regions, for LATE, at least one should be 1 (Yes)
NPTDPB_index=np.where(data_store_title_arr=='NPTDPB')[0][0]
NPTDPC_index=np.where(data_store_title_arr=='NPTDPC')[0][0]
NPTDPE_index=np.where(data_store_title_arr=='NPTDPE')[0][0]

#-------------------------------------------------------------------------------------------
# 2. FTLD with TDP-43 pathology (FTLD-TDP)
#Only using 0 (No) and 1 (Yes), for LATE, it is 0 (No)
FTLD_TDP_index=np.where(data_store_title_arr=='NPFTDTDP')[0][0]

#-------------------------------------------------------------------------------------------
# 3. ALS/motor neuron disease (MND) present?
# No
# 1 Yes, with TDP-43 inclusions in motor neurons
# 2 Yes, with FUS inclusions in motor neurons
# 3 Yes, with SOD1 inclusions in motor neurons
# 4 Yes, with other inclusions
# 5 Yes, with no specific inclusions
# Using 0, 1, 2, 3, 4, and 5, for LATE, it is 0 (No)
ALS_index=np.where(data_store_title_arr=='NPALSMND')[0][0]

# 4. Other FTLD subtype
# Only using 0 (No) and 1 (Yes), for LATE, it is 0 (No)
aFTLD_U_index=np.where(data_store_title_arr=='NPOFTD1')[0][0]
NIFID_index=np.where(data_store_title_arr=='NPOFTD2')[0][0]
BIBD_index=np.where(data_store_title_arr=='NPOFTD3')[0][0]
FTLD_UPS_index=np.where(data_store_title_arr=='NPOFTD4')[0][0]
FTLD_NOS_index=np.where(data_store_title_arr=='NPOFTD5')[0][0]

# 5. AD
CDRGLOB_Index=np.where(data_store_title_arr=='CDRGLOB')[0][0]

In [10]:
NPTDPB_values=data_store_arr[:,NPTDPB_index]
NPTDPC_values=data_store_arr[:,NPTDPC_index]
NPTDPE_values=data_store_arr[:,NPTDPE_index]

Filter_index_1_a=np.unique(np.r_[np.r_[np.where(NPTDPB_values==1)[0],np.where(NPTDPC_values==1)[0]],np.where(NPTDPE_values==1)[0]])
Filter_index_1_b=np.intersect1d(np.intersect1d(np.where(NPTDPB_values==0)[0],np.where(NPTDPC_values==0)[0]),np.where(NPTDPE_values==0)[0])

Filter_index_1=np.r_[Filter_index_1_a,Filter_index_1_b]

Filter_index_1.shape

(10579,)

In [11]:
FTLD_TDP_values=data_store_arr[:,FTLD_TDP_index]
ALS_values=data_store_arr[:,ALS_index]

Filter_index_2_a=np.unique(np.r_[np.r_[np.r_[np.r_[np.r_[np.where(FTLD_TDP_values==1)[0],np.where(ALS_values==1)[0]],np.where(ALS_values==2)[0]],np.where(ALS_values==3)[0]],np.where(ALS_values==4)[0]],np.where(ALS_values==5)[0]])
Filter_index_2_b=np.intersect1d(np.where(FTLD_TDP_values==0)[0],np.where(ALS_values==0)[0])

Filter_index_2=np.r_[Filter_index_2_a,Filter_index_2_b]

Filter_index_2.shape

(13704,)

In [12]:
aFTLD_U_values=data_store_arr[:,aFTLD_U_index]
NIFID_values=data_store_arr[:,NIFID_index]
BIBD_values=data_store_arr[:,BIBD_index]
FTLD_UPS_values=data_store_arr[:,FTLD_UPS_index]
FTLD_NOS_values=data_store_arr[:,FTLD_NOS_index]

Filter_index_3_a=np.intersect1d(np.intersect1d(np.intersect1d(np.intersect1d(np.where(aFTLD_U_values==0)[0],np.where(NIFID_values==0)[0]),np.where(BIBD_values==0)[0]),np.where(FTLD_UPS_values==0)[0]),np.where(FTLD_NOS_values==0)[0])
Filter_index_3_b=np.r_[np.r_[np.r_[np.r_[np.where(aFTLD_U_values==1)[0],np.where(NIFID_values==1)[0]],np.where(BIBD_values==1)[0]],np.where(FTLD_UPS_values==1)[0]],np.where(FTLD_NOS_values==1)[0]]

Filter_index_3=np.r_[Filter_index_3_a,Filter_index_3_b]

Filter_index_3.shape

(16529,)

In [13]:
CDRGLOB_values=data_store_arr[:,CDRGLOB_Index]
Filter_index_4=np.intersect1d(np.where(CDRGLOB_values<=3)[0],np.where(CDRGLOB_values>=1)[0])
Filter_index_4.shape

(40193,)

In [14]:
data_store_arr_Label_index=np.intersect1d(np.intersect1d(np.intersect1d(Filter_index_1,Filter_index_2),Filter_index_3),Filter_index_4)

In [15]:
data_store_arr_Label_index

array([     0,      1,      2, ..., 163189, 163190, 163191])

In [16]:
data_store_arr_Label_index.shape

(4537,)

In [17]:
data_store_arr_Label_=data_store_arr[data_store_arr_Label_index]
data_store_arr_Label_.shape

(4537, 1694)

In [18]:
NACCID_Index=np.where(data_store_title_arr=='NACCID')[0][0]
sample_all_IDs=data_store_arr_Label_[:,NACCID_Index]
sample_IDs=np.unique(sample_all_IDs)
sample_IDs.shape

(1398,)

In [19]:
sample_all_IDs.shape

(4537,)

In [20]:
data_label=[]
test_values=[]
for data_i in data_store_arr_Label_:
    Interested_value=list(data_i)
    
    if (data_i[NPTDPB_index]==1 or data_i[NPTDPC_index]==1 or data_i[NPTDPE_index]==1) and (data_i[FTLD_TDP_index]==0 and data_i[ALS_index]==0 and data_i[aFTLD_U_index]==0 and data_i[NIFID_index]==0 and data_i[BIBD_index]==0 and data_i[FTLD_UPS_index]==0 and data_i[FTLD_NOS_index]==0):
        
        test_values.append([Interested_value[0],data_i[NPTDPB_index],data_i[NPTDPC_index],data_i[NPTDPE_index]])
        # LATE
        data_i_label=Interested_value+[1]
    else:
        # Non-LATE
        data_i_label=Interested_value+[0]
    data_label.append(data_i_label)

In [21]:
test_values

[['NACC040968', 1, 1, 0],
 ['NACC040968', 1, 1, 0],
 ['NACC040968', 1, 1, 0],
 ['NACC066332', 1, 1, 0],
 ['NACC079538', 1, 1, 1],
 ['NACC087608', 1, 1, 8],
 ['NACC087608', 1, 1, 8],
 ['NACC178487', 1, 0, 1],
 ['NACC178487', 1, 0, 1],
 ['NACC178487', 1, 0, 1],
 ['NACC300260', 1, 1, 0],
 ['NACC300260', 1, 1, 0],
 ['NACC300260', 1, 1, 0],
 ['NACC300260', 1, 1, 0],
 ['NACC300260', 1, 1, 0],
 ['NACC477210', 1, 1, 0],
 ['NACC477210', 1, 1, 0],
 ['NACC477210', 1, 1, 0],
 ['NACC477210', 1, 1, 0],
 ['NACC477210', 1, 1, 0],
 ['NACC502235', 1, 1, 8],
 ['NACC502235', 1, 1, 8],
 ['NACC601952', 1, 8, 8],
 ['NACC613505', 1, 1, 1],
 ['NACC613505', 1, 1, 1],
 ['NACC613505', 1, 1, 1],
 ['NACC618592', 1, 0, 0],
 ['NACC618592', 1, 0, 0],
 ['NACC643852', 1, 1, 0],
 ['NACC643852', 1, 1, 0],
 ['NACC643852', 1, 1, 0],
 ['NACC643852', 1, 1, 0],
 ['NACC643852', 1, 1, 0],
 ['NACC755332', 1, 1, 8],
 ['NACC755332', 1, 1, 8],
 ['NACC755332', 1, 1, 8],
 ['NACC755332', 1, 1, 8],
 ['NACC755332', 1, 1, 8],
 ['NACC77078

In [22]:
np.where(np.array(test_values)[:,0]=='NACC023681')[0]

array([], dtype=int64)

In [23]:
np.array(test_values)[np.where(np.array(test_values)[:,0]=='NACC023681')[0],:]

array([], shape=(0, 4), dtype='<U21')

In [24]:
np.array(test_values)[np.where(np.array(test_values)[:,0]=='NACC025315')[0],:]

array([['NACC025315', '8', '1', '8'],
       ['NACC025315', '8', '1', '8']], dtype='<U21')

In [25]:
np.where(np.array(data_store_arr)[:,0]=='NACC025315')

(array([27624, 27625, 27626, 27627]),)

In [26]:
np.where(np.array(data_store_arr)[:,0]=='NACC023681')

(array([27601, 27602, 27603, 27604, 27605, 27606, 27607, 27608, 27609,
        27610]),)

In [27]:
data_label_arr=np.array(data_label)
print(data_label_arr.shape)

(4537, 1695)


In [28]:
label_values=[0,1]
label_names=['Non-LATE','pure LATE']
for label_i in label_values:
    print(label_names[label_i]+":",np.sum(data_label_arr[:,-1].astype(int)==label_i))

Non-LATE: 2807
pure LATE: 1730


In [29]:
# Got all pure LATE IDs
sample_LATE_IDs=data_label_arr[np.where(data_label_arr[:,-1].astype(int)==1)[0],0]
sample_LATE_IDs.shape

(1730,)

In [30]:
sample_LATE=data_store_arr_Label_[np.where(data_label_arr[:,-1].astype(int)==1)[0],:]
sample_LATE.shape

(1730, 1694)

In [31]:
sample_LATE_IDs_Unique=np.unique(sample_LATE_IDs)
sample_LATE_IDs_Unique.shape

(475,)

In [32]:
sample_LATE

array([['NACC040968', 5, 784, ..., nan, nan, nan],
       ['NACC040968', 5, 1193, ..., nan, nan, nan],
       ['NACC040968', 5, 1868, ..., nan, nan, nan],
       ...,
       ['NACC990396', 4, 468, ..., nan, nan, nan],
       ['NACC990396', 4, 805, ..., nan, nan, nan],
       ['NACC990396', 4, 1217, ..., nan, nan, nan]], dtype=object)

In [33]:
np.array(sample_LATE)[np.where(np.array(sample_LATE)[:,0]=='NACC025315')[0],:]

array([['NACC025315', 4, 720, ..., nan, nan, nan],
       ['NACC025315', 4, 1099, ..., nan, nan, nan]], dtype=object)

In [34]:
np.array(sample_LATE)[np.where(np.array(sample_LATE)[:,0]=='NACC025315')[0],NPTDPB_index]

array([8, 8], dtype=object)

In [35]:
np.array(sample_LATE)[np.where(np.array(sample_LATE)[:,0]=='NACC025315')[0],NPTDPC_index]

array([1, 1], dtype=object)

In [36]:
np.array(sample_LATE)[np.where(np.array(sample_LATE)[:,0]=='NACC025315')[0],NPTDPE_index]

array([8, 8], dtype=object)

In [37]:
data_store_title_arr_new=np.append(data_store_title_arr,np.array(['SurvivalTime','Event']))

In [38]:
output_path="./data/survival_data.csv"
title=data_store_title_arr_new
write_to_csv(title.reshape(1,title.shape[0]),output_path)

In [39]:
for sample_LATE_IDs_Unique_i in sample_LATE_IDs_Unique:
    #print("Current ID: ",sample_IDs_i)
    
    sample_LATE_IDs_Unique_i_index_=np.where(sample_LATE_IDs==sample_LATE_IDs_Unique_i)[0]
    
    # CDRGLOB
    #Original UDS question
    #Global CDR
    #Numeric longitudinal
    #0.0 = No impairment
    #0.5 = Questionable impairment
    #1.0 = Mild impairment
    #2.0 = Moderate impairment
    #3.0 = Severe impairment

    NACCFDYS_Index=np.where(data_store_title_arr=='NACCFDYS')[0]
    NACCFDY_arr_get=sample_LATE[sample_LATE_IDs_Unique_i_index_,NACCFDYS_Index]
    
    combine_temp_arr=np.c_[sample_LATE_IDs_Unique_i_index_,NACCFDY_arr_get]
    sample_LATE_IDs_Unique_i_index=combine_temp_arr[combine_temp_arr[:,1].argsort()][:,0].astype(int)

    CDRGLOB_Index=np.where(data_store_title_arr=='CDRGLOB')[0][0]
    CDRGLOB_arr_get_=sample_LATE[sample_LATE_IDs_Unique_i_index,CDRGLOB_Index]
    CDRGLOB_arr_get=np.array([3 if i==2 else i for i in CDRGLOB_arr_get_])  

    #NACC derived variable
    #Days from initial visit to each follow-up visit
    #Numeric longitudinal
    #0–5000
    #This variable provides the number of days from the initial visit to each follow-up visit, calculated as visit date less initial visit date, for every follow-up visit. All initial visits will have naccfdys = 0. Note that in order to obtain follow-up time in years, simply divide naccfdys by 365.25. This variable is available for all UDS subjects at all visits.

    NACCFDY_arr_get=sample_LATE[sample_LATE_IDs_Unique_i_index,NACCFDYS_Index]
    
    if np.max(CDRGLOB_arr_get)-CDRGLOB_arr_get[0]>0:
        max_index=np.argmax(CDRGLOB_arr_get)
    
        data_store_arr_new_=sample_LATE[sample_LATE_IDs_Unique_i_index[max_index],:]
        Survival_time=NACCFDY_arr_get[max_index]
        Event=True
                
    elif np.max(CDRGLOB_arr_get)-CDRGLOB_arr_get[0]==0:
    
        max_index=np.argmax(NACCFDY_arr_get)
    
        data_store_arr_new_=sample_LATE[sample_LATE_IDs_Unique_i_index[max_index],:]
        Survival_time=NACCFDY_arr_get[max_index]
        Event=False
    
    else:
        print('error')
        
    data_store_arr_new=np.append(np.append(data_store_arr_new_,Survival_time),Event)
    write_to_csv(data_store_arr_new.reshape(1,data_store_arr_new.shape[0]),output_path)