In [1]:
import pandas as pd
import numpy as np

csv_data = pd.read_csv('cheng10142021.csv')
print(csv_data.shape) 

/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3441: DtypeWarning: Columns (19,21,23,25,27,40,43,45,47,50,60,62,64,66,68,70,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,133,155,164,175,178,188,216,219,221,223,225,227,229,231,233,235,237,239,241,243,245,247,249,251,253,255,257,259,261,263,265,267,269,271,381,396,398,400,418,420,422,431,444,453,493,566,574,599,635,651,665,668,671,676,688,699,705,707,792,798,800,801,984,986,988,989,991,998,1000,1002,1003,1010,1012,1014,1016,1017,1024,1039,1053,1067,1081,1083,1089,1090,1091,1092,1098,1099,1107,1118,1120,1122,1124,1130,1191,1246,1247,1248,1256,1257,1258,1259,1269,1291,1294,1297,1333,1349,1351,1353,1355,1357,1359,1361,1363,1365,1367,1369,1371,1373,1375,1377,1379,1381,1383,1385,1387,1389,1391,1393,1395,1397,1399,1401,1403,1453,1454,1456,1457,1460,1461,1464,1465,1468,1469,1472,1473,1547,1606,1615,1617,1619,1621,1632,1634,1636,1644,1646,1648,1650,1658,1660,1662,1664,1690) h

(163199, 1727)


In [2]:
col_title=csv_data.columns.values.tolist()

In [3]:
col_title_arr=np.array(col_title)

In [4]:
for i in col_title_arr:
    print(i)

NACCID
NACCADC
PACKET
FORMVER
VISITMO
VISITDAY
VISITYR
NACCVNUM
NACCAVST
NACCNVST
NACCDAYS
NACCFDYS
NACCREAS
NACCREFR
BIRTHMO
BIRTHYR
SEX
HISPANIC
HISPOR
HISPORX
RACE
RACEX
RACESEC
RACESECX
RACETER
RACETERX
PRIMLANG
PRIMLANX
EDUC
MARISTAT
NACCLIVS
INDEPEND
RESIDENC
HANDED
INBIRMO
INBIRYR
INSEX
NEWINF
INHISP
INHISPOR
INHISPOX
NACCNINR
INRACE
INRACEX
INRASEC
INRASECX
INRATER
INRATERX
INEDUC
INRELTO
INRELTOX
INKNOWN
INLIVWTH
INVISITS
INCALLS
INRELY
NACCFAM
NACCMOM
NACCDAD
NACCAM
NACCAMX
NACCAMS
NACCAMSX
NACCFM
NACCFMX
NACCFMS
NACCFMSX
NACCOM
NACCOMX
NACCOMS
NACCOMSX
NACCFADM
NACCFFTD
ANYMEDS
DRUG1
DRUG2
DRUG3
DRUG4
DRUG5
DRUG6
DRUG7
DRUG8
DRUG9
DRUG10
DRUG11
DRUG12
DRUG13
DRUG14
DRUG15
DRUG16
DRUG17
DRUG18
DRUG19
DRUG20
DRUG21
DRUG22
DRUG23
DRUG24
DRUG25
DRUG26
DRUG27
DRUG28
DRUG29
DRUG30
DRUG31
DRUG32
DRUG33
DRUG34
DRUG35
DRUG36
DRUG37
DRUG38
DRUG39
DRUG40
TOBAC30
TOBAC100
SMOKYRS
PACKSPER
QUITSMOK
ALCOCCAS
ALCFREQ
CVHATT
HATTMULT
HATTYEAR
CVAFIB
CVANGIO
CVBYPASS
CVPACDEF
CVPACE
CVCHF
CV

In [ ]:
aa=col_title_arr.astype(object)
#np.savetxt("result1.txt", aa,delimiter=' ')

In [5]:
col_title_arr.shape

(1727,)

In [7]:
np.where(col_title_arr=='NACCAPOE')

(array([1094]),)

In [11]:
np.where(col_title_arr=='NACCNE4S')

(array([1096]),)

In [8]:
col_title_arr[1094]

'NACCAPOE'

In [12]:
col_title_arr.shape

(1727,)

In [13]:
np.array(csv_data).shape

(163199, 1727)

In [14]:
np.array(csv_data)[:,1094]

array([1, 1, 1, ..., 1, 1, 1], dtype=object)

In [15]:
np.array(csv_data)[:,1096]

array([0, 0, 0, ..., 0, 0, 0], dtype=object)

In [ ]:
np.where(col_title_arr=='ALCOCCAS')

In [ ]:
np.where(col_title_arr=='ALCFREQ')

In [ ]:
np.where(col_title_arr=='ALCOHOL')

In [ ]:
np.where(col_title_arr=='ALCDEM')

In [ ]:
np.where(col_title_arr=='FTLDSUBT')

In [ ]:
np.where(csv_data_arr[:,598]==2)

In [ ]:
csv_data_arr[:,598][np.array([87,100,101,111,112])]

In [ ]:
np.sum(csv_data_arr[:,598]==2)

In [ ]:
csv_data_arr[:,598].shape

In [ ]:
np.where(col_title_arr=='FTLDSUBX')

In [ ]:
csv_data_arr[:,599]

In [ ]:
csv_data_arr[:,599].shape

In [ ]:
import pandas as pd
np.sum(pd.isna(csv_data_arr[:,599])) 

In [ ]:
for k in csv_data_arr[:,599]:
    if not pd.isna(k):
        print(k)

In [ ]:
len(csv_data_arr[:,599])

In [ ]:
np.where(csv_data_arr[:,599]==3)

In [ ]:
csv_data_arr[:,599]

In [ ]:
np.sum(csv_data_arr[:,599]=='3')

In [ ]:
len(csv_data_arr[:,599][0])

In [ ]:
csv_data_arr=np.array(csv_data)

In [ ]:
csv_data_arr