In [1]:
import pandas as pd
import numpy as np
import gc

In [2]:
def csv_read(p_path):
    pd_data=pd.read_csv(p_path, sep=',')
    column_names=pd_data.columns.values.tolist()
    print(column_names)
    return pd_data,column_names

def write_to_csv(p_data,p_path):
    dataframe = pd.DataFrame(p_data)
    dataframe.to_csv(p_path, mode='a',header=False,index=False,sep=',')
    del dataframe
    gc.collect()

In [3]:
data,column_names=csv_read('./data/survival_data.csv')

['NACCID', 'NACCAVST', 'NACCFDYS', 'NACCREAS', 'NACCREFR', 'BIRTHMO', 'BIRTHYR', 'SEX', 'HISPANIC', 'HISPOR', 'HISPORX', 'RACE', 'RACEX', 'RACESEC', 'RACESECX', 'RACETER', 'RACETERX', 'PRIMLANG', 'PRIMLANX', 'EDUC', 'MARISTAT', 'NACCLIVS', 'INDEPEND', 'RESIDENC', 'HANDED', 'INBIRMO', 'INBIRYR', 'INSEX', 'NEWINF', 'INHISP', 'INHISPOR', 'INHISPOX', 'NACCNINR', 'INRACE', 'INRACEX', 'INRASEC', 'INRASECX', 'INRATER', 'INRATERX', 'INEDUC', 'INRELTO', 'INRELTOX', 'INKNOWN', 'INLIVWTH', 'INVISITS', 'INCALLS', 'INRELY', 'NACCFAM', 'NACCMOM', 'NACCDAD', 'NACCAM', 'NACCAMX', 'NACCAMS', 'NACCAMSX', 'NACCFM', 'NACCFMX', 'NACCFMS', 'NACCFMSX', 'NACCOM', 'NACCOMX', 'NACCOMS', 'NACCOMSX', 'NACCFADM', 'NACCFFTD', 'ANYMEDS', 'DRUG1', 'DRUG2', 'DRUG3', 'DRUG4', 'DRUG5', 'DRUG6', 'DRUG7', 'DRUG8', 'DRUG9', 'DRUG10', 'DRUG11', 'DRUG12', 'DRUG13', 'DRUG14', 'DRUG15', 'DRUG16', 'DRUG17', 'DRUG18', 'DRUG19', 'DRUG20', 'DRUG21', 'DRUG22', 'DRUG23', 'DRUG24', 'DRUG25', 'DRUG26', 'DRUG27', 'DRUG28', 'DRUG29', 'D

In [4]:
len(column_names)

1696

In [5]:
np.where(np.array(column_names)=='CDRGLOB')

(array([270]),)

In [6]:
Del_indexes=['NACCID','HISPORX','RACEX','RACESECX','RACETERX','PRIMLANX','INHISPOX','INRACEX','INRASECX','INRATERX','INRELTOX','NACCAMX','NACCAMSX','NACCFMX','NACCFMSX','NACCOMX','NACCOMSX','CVOTHRX','NCOTHRX','ARTHTYPX','OTHSLEEX','ABUSX','PSYCDISX','CVDIMAGX','SPEECHX','FACEXPX', 'TRESTFAX', 'TRESTRHX', 'TRESTLHX', 'TRESTRFX', 'TRESTLFX', 'TRACTRHX', 'TRACTLHX', 'RIGDNEX',  'RIGDUPRX', 'RIGDUPLX', 'RIGDLORX', 'RIGDLOLX', 'TAPSRTX', 'TAPSLFX', 'HANDMVRX', 'HANDMVLX', 'HANDATRX', 'HANDATLX', 'LEGRTX','LEGLFX',  'ARISINGX', 'POSTUREX','GAITX', 'POSSTABX','BRADYKIX','NPIQINFX','OTHNEURX','COGOTHRX','NACCCGFX', 'COGMODEX', 'BEOTHRX', 'NACCBEFX', 'BEMODEX','MOMODEX','MMSELANX','NPSYLANX', 'MOCALANX','OTHBIOMX','OTHMUTX','FTLDSUBX','OTHPSYX','COGOTHX','COGOTH2X', 'COGOTH3X','ARTYPEX', 'SLEEPOTX', 'ANTIENCX', 'OTHCONDX','RESPOTHX','FTDLTFAS', 'FTDLIMB', 'FTDBULB', 'FTDGSEV', 'FTDGSEVX', 'FTDGTYP', 'FTDGTYPG', 'FTDGTYPX', 'FTDPPASL', 'FTDPPAPO', 'FTDPPAIW', 'FTDPPASW', 'FTDPPAPK', 'FTDPPAGS', 'FTDPPAEH', 'FTDPPACS', 'FTDPPASS', 'FTDPPASR', 'FTDPPASD', 'FTDCPPA', 'FTDCPPAS', 'FTDBVCLN', 'FTDBVDIS', 'FTDBVAPA', 'FTDBVLOS', 'FTDBVRIT', 'FTDBVHYP', 'FTDBVNEU', 'FTDBVIDL', 'FTDBVFT', 'FTDEMGPV', 'FTDEMGPY', 'FTDEMGMN', 'FTDPABVF', 'FTDWORRC', 'FTDWORRS', 'FTDWORRR', 'FTDWORIC', 'FTDWORIS', 'FTDWORIR', 'FTDWORIP', 'FTDSEMMT', 'FTDSEMAA', 'FTDSEMTA', 'FTDSEMSU', 'FTDANASW', 'FTDANAOW', 'FTDANATS', 'FTDSENAS', 'FTDSENOS', 'FTDSENSR', 'FTDSENPR', 'FTDNOUNC', 'FTDVERBC', 'FTDRATIO', 'FTDREAAS', 'FTDREAOS', 'FTDREASR', 'FTDREAPR', 'FTDCPC2F', 'FTDHAIRD', 'FTDSPIT', 'FTDNOSE', 'FTDCOAGE', 'FTDCRY', 'FTDCUT', 'FTDYTRIP', 'FTDEATP', 'FTDTELLA', 'FTDOPIN', 'FTDLAUGH', 'FTDSHIRT', 'FTDKEEPM', 'FTDPICKN', 'FTDOVER', 'FTDEATR', 'FTDHAIRL', 'FTDSHIRW', 'FTDMOVE', 'FTDHUGS', 'FTDLOUD', 'FTDLOST', 'FTDSNTOT', 'FTDSNTBS', 'FTDSNTOS', 'FTDSNRAT', 'FTDSELF', 'FTDBADLY', 'FTDDEPR', 'FTDEMOTD', 'FTDLSELF', 'FTDDISR', 'FTDBELCH', 'FTDGIGG', 'FTDPRIV', 'FTDNEGAT', 'FTDECOMM', 'FTDINAPJ', 'FTDFAILA', 'FTDRESIS', 'FTDINTER', 'FTDVERBA', 'FTDPHYSI', 'FTDTOPIC', 'FTDPROTO', 'FTDPREO', 'FTDFINI', 'FTDACTED', 'FTDABS', 'FTDFEEDB', 'FTDFRUST', 'FTDANXI', 'FTDNERVO', 'FTDNDIAG', 'FTDSTIMB', 'FTDSTIME', 'FTDOBJEC', 'FTDCIRCU', 'FTDPERSE', 'FTDREPEA', 'FTDANECD', 'FTDDINIT', 'FTDDELAY', 'FTDADDVE', 'FTDFLUCT', 'FTDLOSTT', 'FTDREPRU', 'FTDTRAIN', 'FTDDISCL', 'FTDSPONT', 'FTDSPONR', 'FTDSTOOD', 'FTDTOUCH', 'FTDDSOCI', 'FTDEXAGG', 'FTDSBTOT', 'FTDSBCTO', 'FTDLENGT', 'FTDCPC4F', 'FTDWORKU', 'FTDMIST', 'FTDCRIT', 'FTDWORR', 'FTDBAD', 'FTDPOOR', 'FTDFFEAR', 'FTDBIST', 'FTDCPC5F', 'FTDINSEX', 'FTDINFYR', 'FTDINFMO', 'FTDINFRE', 'FTDFEEL', 'FTDDIFF', 'FTDSORR', 'FTDSIDE', 'FTDADVAN', 'FTDIMAG', 'FTDMISF', 'FTDWASTE', 'FTDPITY', 'FTDQTOUC', 'FTDSIDES', 'FTDSOFTH', 'FTDUPSET', 'FTDCRITI', 'FTDIRIEC', 'FTDIRIPT', 'FTDCPC6F', 'FTDALTER', 'FTDEMOT', 'FTDACROS', 'FTDCONV', 'FTDINTUI', 'FTDJOKE', 'FTDIMAGP', 'FTDINAPP', 'FTDCHBEH', 'FTDADBEH', 'FTDLYING', 'FTDGOODF', 'FTDREGUL', 'FTDSMSCR', 'FTDSPSCR', 'FTDRSMST', 'FTDSMRI', 'FTDSMDY', 'FTDSMYR', 'FTDSMMO', 'FTDSMDIC', 'FTDSMDIS', 'FTDSMADN', 'FTDSMADV', 'FTDSMMAN', 'FTDSMMAO', 'FTDSMMAM', 'FTDSMFS', 'FTDSMFSO', 'FTDSMQU', 'FTDFDGPT', 'FTDFPYR', 'FTDFPMO', 'FTDFPDY', 'FTDFDDIC', 'FTDFDDID', 'FTDFDADN', 'FTDFDADV', 'FTDFDMAN', 'FTDFDMAO', 'FTDFDMAM', 'FTDFDQU', 'FTDAMYPT', 'FTDAMDY', 'FTDAMYR', 'FTDAMMO', 'FTDAMDIC', 'FTDAMDID', 'FTDAMLIG', 'FTDAMLIO', 'FTDAMADN', 'FTDAMADV', 'FTDAMMAN', 'FTDAMMAO', 'FTDAMMAM', 'FTDAMQU', 'FTDOTHER', 'FTDOTDOP', 'FTDOTSER', 'FTDOTCHO', 'FTDOTANO', 'FTDOTANS', 'FTDIDIAG', 'FTDSMRIO', 'FTDMRIFA', 'FTDMRIRF', 'FTDMRILF', 'FTDMRIRT', 'FTDMRILT', 'FTDMRIRM', 'FTDMRILM', 'FTDMRIRP', 'FTDMRILP', 'FTDMRIRB', 'FTDMRILB', 'FTDMRIOB', 'FTDMRIOS', 'FTDFDGPE', 'FTDFDGFH', 'FTDFDGRF', 'FTDFDGLF', 'FTDFDGRT', 'FTDFDGLT', 'FTDFDGRM', 'FTDFDGLM', 'FTDFDGRP', 'FTDFDGLP', 'FTDFDGRB', 'FTDFDGLB', 'FTDFDGOA', 'FTDFDGOS', 'FTDAMYP', 'FTDAMYVI', 'FTDAMYRF', 'FTDAMYLF', 'FTDAMYRT', 'FTDAMYLT', 'FTDAMYRM', 'FTDAMYLM', 'FTDAMYRP', 'FTDAMYLP', 'FTDAMYRB', 'FTDAMYLB', 'FTDAMYOA', 'FTDAMYOS', 'FTDCBFSP', 'FTDCBFVI', 'FTDCBFRF', 'FTDCBFLF', 'FTDCBFRT', 'FTDCBFLT', 'FTDCBFRM', 'FTDCBFLM', 'FTDCBFRP', 'FTDCBFLP', 'FTDCBFRB', 'FTDCBFLB', 'FTDCBFOA', 'FTDCBFOS', 'FTDOTHI', 'FTDOTHIS','NGDSWGAC', 'NGDSWEAC', 'NGDSGWAC', 'NGDSEXAC', 'NGDSEXOM','ADGCGWAS','NGDSGWAS','ADGCEXR','ADGCRND','NGDSWGS','NGDSWES','ADGCEXOM','NPSEX','NPFIXX','NPTANX', 'NPABANX', 'NPASANX', 'NPTDPANX','NPHISOX', 'NPPATHOX', 'NPFAUT1', 'NPFAUT2', 'NPFAUT3', 'NPFAUT4','NPNIT', 'NPCERAD', 'NPADRDA', 'NPOCRIT','NPOTH1X',  'NPOTH2X', 'NPOTH3X','LBSSALIV', 'LBSSWALL', 'LBSINSEX', 'LBSPRSEX', 'LBSWEIGH', 'LBSSMELL', 'LBSSWEAT', 'LBSTOLCD', 'LBSTOLHT', 'LBSDBVIS', 'LBSCONST', 'LBSHDSTL', 'LBSLSSTL', 'LBSUBLAD', 'LBSUSTRM', 'LBSUPASS', 'LBSDZSTU', 'LBSDZSTN', 'LBSFAINT', 'LBSPSYM', 'LBPSYAGE', 'LBSSUPSY', 'LBSSUPDI', 'LBSSUPHT', 'LBSSTNSY', 'LBSSTNDI', 'LBSSTNHT', 'LBSAGERM', 'LBSAGESM', 'LBSAGEGT', 'LBSAGEFL', 'LBSAGETR', 'LBSAGEBR', 'LBSSCLAU', 'LBSSCLVR', 'LBSSCLOT', 'LBSSCOR', 'LBUDSPCH', 'LBUDSALV', 'LBUDSWAL', 'LBUWRITE', 'LBUDFOOD', 'LBUDRESS', 'LBUDHYGN', 'LBUDTURN', 'LBUDFALL', 'LBUDFRZ', 'LBUDWALK', 'LBUDTREM', 'LBUDSENS', 'LBUMSPCH', 'LBUMSPCX', 'LBUMFACE', 'LBUMFACX', 'LBUMTRFA', 'LBUTRFAX', 'LBUMTRRH', 'LBUTRRHX', 'LBUMTRLH', 'LBUTRLHX', 'LBUMTRRF', 'LBUTRRFX', 'LBUMTRLF', 'LBUTRLFX', 'LBUMATRH', 'LBUATRHX', 'LBUMATLH', 'LBUATLHX', 'LBUMRGNK', 'LBURGNKX', 'LBUMRGRU', 'LBURGRUX', 'LBUMRGLU', 'LBURGLUX', 'LBUMRGRL', 'LBURGRLX', 'LBUMRGLL', 'LBURGLLX', 'LBUMFTRH', 'LBUFTRHX', 'LBUMFTLH', 'LBUFTLHX', 'LBUMHMRH', 'LBUHMRHX', 'LBUMHMLH', 'LBUHMLHX', 'LBUMPSRH', 'LBUPSRHX', 'LBUMPSLH', 'LBUPSLHX', 'LBUMLGRL', 'LBULGRLX', 'LBUMLGLL', 'LBULGLLX', 'LBUMRISE', 'LBUMRISX', 'LBUMPOST', 'LBUMPOSX', 'LBUMGAIT', 'LBUMGAIX', 'LBUPSTBL', 'LBUPSTBX', 'LBUMBRAD', 'LBUMBRAX', 'LBUMHNYR', 'LBUMHNYX', 'LBDELUS', 'LBDHURT', 'LBDSTEAL', 'LBDAFFR', 'LBDGUEST', 'LBDIMPOS', 'LBDHOME', 'LBDABAND', 'LBDPRES', 'LBDOTHER', 'LBDELFRQ', 'LBDELSEV', 'LBDELDST', 'LBHALL', 'LBHVOICE', 'LBHPEOPL', 'LBHNOTPR', 'LBHODOR', 'LBHFEEL', 'LBHTASTE', 'LBHOTSEN', 'LBHALFRQ', 'LBHALSEV', 'LBHALDST', 'LBANXIET', 'LBANEVNT', 'LBANRELX', 'LBANBRTH', 'LBANBUTT', 'LBANPLAC', 'LBANSEPR', 'LBANOTHR', 'LBANXFRQ', 'LBANXSEV', 'LBANXDST', 'LBAPATHY', 'LBAPSPNT', 'LBAPCONV', 'LBAPAFF', 'LBAPCHOR', 'LBAPINT', 'LBAPFAML', 'LBAPINTR', 'LBAPOTH', 'LBAPAFRQ', 'LBAPASEV', 'LBAPADST', 'LBDOPAM', 'LBDAGE', 'LBDDRUG1', 'LBDDOSE1', 'LBDAGE2', 'LBDDRUG2', 'LBDDOSE2', 'LBDELAGE', 'LBDELMED', 'LBDELMD1', 'LBDELMD2', 'LBHALAGE', 'LBHALMED', 'LBHALMD1', 'LBHALMD2', 'LBANXAGE', 'LBANXMED', 'LBANXMD1', 'LBANXMD2', 'LBAPAAGE', 'LBAPAMED', 'LBAPAMD1', 'LBAPAMD2', 'LBMLTHRG', 'LBMSLEEP', 'LBMDISRG', 'LBMSTARE', 'LBSPCGIM', 'LBSPDRM', 'LBSPYRS', 'LBSPMOS', 'LBSPINJS', 'LBSPINJP', 'LBSPCHAS', 'LBSPMOVE', 'LBSPLEGS', 'LBSPNERV', 'LBSPURGL', 'LBSPSENS', 'LBSPWORS', 'LBSPWALK', 'LBSPAWAK', 'LBSPBRTH', 'LBSPTRT', 'LBSPCRMP', 'LBSPALRT', 'LBSCLIV', 'LBSCSLP', 'LBSCBEHV', 'LBSCDRM', 'LBSCYRS', 'LBSCMOS', 'LBSCINJS', 'LBSCINJP', 'LBSCCHAS', 'LBSCMOVE', 'LBSCLEGS', 'LBSCNERV', 'LBSCSENS', 'LBSCWORS', 'LBSCWALK', 'LBSCAWAK', 'LBSCBRTH', 'LBSCTRT', 'LBSCCRMP', 'LBSCALRT','PACOGIMP', 'PANSFALL', 'PANSWKOF', 'PANSLYAW', 'PANSWKER', 'PANSLTTL', 'SCPARATE', 'PADSUNEX', 'PADSSITP', 'PADSWATV', 'PADSTALK', 'PADSAWDY', 'PADSFLDY', 'CONSFALL', 'CONSWKOF', 'CONSLYAW', 'CONSWKER', 'CONSLTTL', 'SCCORATE', 'CODSUNEX', 'CODSSITP', 'CODSWATV', 'CODSTALK', 'CODSAWDY', 'CODSFLDY', 'SCCOFRST', 'SCCOAGEN', 'SCCOAGED', 'SCCOCOMP', 'SCCOSCVR', 'SCCOOTH', 'SCCOSCOR', 'LBNSWORD', 'LBNSCOLR', 'LBNSCLWD', 'LBNPFACE', 'LBNPNOIS', 'LBNPTCOR', 'LBNPPARD', 'LBCDSCOG', 'LBCCMEM', 'LBCCLANG', 'LBCCATT', 'LBCCEXDE', 'LBCCVIS', 'LBCDSMOV', 'LBCMBRAD', 'LBCMRIGD', 'LBCMRTRM', 'LBCMPTRM', 'LBCMATRM', 'LBCMMYOC', 'LBCMGAIT', 'LBCMPINS', 'LBCDSBEV', 'LBCBDEP', 'LBCBAPA', 'LBCBANX', 'LBCBHALL', 'LBCBDEL', 'LBCDSAUT', 'LBCAREM', 'LBCAAPN', 'LBCALGSL', 'LBCARSLE', 'LBCADTSL', 'LBCACGFL', 'LBCAHYPT', 'LBCACONS', 'LBCAHYPS', 'LBCAFALL', 'LBCASYNC', 'LBCASNAP', 'LBCOGST', 'LBCOGDX', 'LBGLRRK2', 'LBGLRKIS', 'LBGPARK2', 'LBGPK2IS', 'LBGPARK7', 'LBGPK7IS', 'LBGPINK1', 'LBGPNKIS', 'LBGSNCA', 'LBGSNCIS', 'LBGGBA', 'LBGGBAIS', 'LBGOTHR', 'LBGOTHIS', 'LBGOTHX', 'LBISMRI', 'LBISMMO', 'LBISMDY', 'LBISMYR', 'LBISMQAV', 'LBISMHIP', 'LBISMAVL', 'LBISMDCM', 'LBISMFMT', 'LBISMADN', 'LBISMVER', 'LBISMMAN', 'LBISMOM', 'LBISMSTR', 'LBISMOS', 'LBIFPET', 'LBIFPYR', 'LBIFPMO', 'LBIFPDY', 'LBIFPQAV', 'LBIFPOCC', 'LBIFPTPP', 'LBIFPISL', 'LBIFPAVL', 'LBIFPDCM', 'LBIFPFMT', 'LBIFPADN', 'LBIFPVER', 'LBIFPMAN', 'LBIFPOM', 'LBIAPET', 'LBIAPYR', 'LBIAPMO', 'LBIAPDY', 'LBIAPQAV', 'LBIAPAVL', 'LBIAPDCM', 'LBIAPFMT', 'LBIAPLIG', 'LBIAPOL', 'LBIAPADN', 'LBIAPVER', 'LBIAPMAN', 'LBIAPOM', 'LBITPET', 'LBITPDY', 'LBITPYR', 'LBITPMO', 'LBITPQAV', 'LBITPAVL', 'LBITPDCM', 'LBITPFMT', 'LBITPLIG', 'LBITPOL', 'LBITPADN', 'LBITPVER', 'LBITPMAN', 'LBITPOM', 'LBIDATS', 'LBIDSYR', 'LBIDSMO', 'LBIDSDY', 'LBIDSQAV', 'LBIDSABN', 'LBOPOLYS', 'LBOPOSYR', 'LBOPOSMO', 'LBOPOSDY', 'LBOPOPOS', 'LBOPOAVL', 'LBOCMIBG', 'LBOCMYR', 'LBOCMMO', 'LBOCMDY', 'LBOCMPOS', 'LBOCMAVL', 'LBOANOS', 'LBOANYR', 'LBOANMO', 'LBOANDY', 'LBOANPOS', 'LBOANAVL', 'LBOANVER', 'LBOANOTH', 'LBOEEG', 'LBOEGYR', 'LBOEGMO', 'LBOEGDY', 'LBOEGPOS', 'LBOEGAVL', 'LBOMSLT', 'LBOMSYR', 'LBOMSMO', 'LBOMSDY', 'LBOMSPOS', 'LBOMSAVL', 'LBOTILT', 'LBOTLYR', 'LBOTLMO', 'LBOTLDY', 'LBOTLPOS', 'LBOTLAVL', 'LBOQSART', 'LBOQSYR', 'LBOQSMO', 'LBOQSDY', 'LBOQSPOS', 'LBOSGAVL', 'LBOTHERM', 'LBOTHDY', 'LBOTHYR', 'LBOTHMO', 'LBOTHPOS', 'LBOTHAVL', 'LBOCGAIT', 'LBOCGYR', 'LBOCGMO', 'LBOCGDY', 'LBOCGPOS', 'LBOCGAVL','NPVOTH', 'NPLEWYCS', 'NPGENE', 'NPFHSPEC', 'NPTAUHAP', 'NPPRNP', 'NPCHROM', 'NPPNORM', 'NPCNORM', 'NPPADP', 'NPCADP', 'NPPAD', 'NPCAD', 'NPPLEWY', 'NPCLEWY', 'NPPVASC', 'NPCVASC', 'NPPFTLD', 'NPCFTLD', 'NPPHIPP', 'NPCHIPP', 'NPPPRION', 'NPCPRION', 'NPPOTH1', 'NPCOTH1', 'NPPOTH2', 'NPCOTH2', 'NPPOTH3', 'NPCOTH3','OTHCOGX','CANCSITE','NACCFDYS']#CDRGLOB

In [7]:
len(Del_indexes)

857

In [8]:
data.shape

(304, 1696)

In [9]:
data_store=data.copy()
data_store_=data_store.drop(Del_indexes, axis=1)
data_store_.shape

(304, 839)

In [10]:
data_store_title=data_store_.columns.values.tolist()

In [11]:
data_store_title

['NACCAVST',
 'NACCREAS',
 'NACCREFR',
 'BIRTHMO',
 'BIRTHYR',
 'SEX',
 'HISPANIC',
 'HISPOR',
 'RACE',
 'RACESEC',
 'RACETER',
 'PRIMLANG',
 'EDUC',
 'MARISTAT',
 'NACCLIVS',
 'INDEPEND',
 'RESIDENC',
 'HANDED',
 'INBIRMO',
 'INBIRYR',
 'INSEX',
 'NEWINF',
 'INHISP',
 'INHISPOR',
 'NACCNINR',
 'INRACE',
 'INRASEC',
 'INRATER',
 'INEDUC',
 'INRELTO',
 'INKNOWN',
 'INLIVWTH',
 'INVISITS',
 'INCALLS',
 'INRELY',
 'NACCFAM',
 'NACCMOM',
 'NACCDAD',
 'NACCAM',
 'NACCAMS',
 'NACCFM',
 'NACCFMS',
 'NACCOM',
 'NACCOMS',
 'NACCFADM',
 'NACCFFTD',
 'ANYMEDS',
 'DRUG1',
 'DRUG2',
 'DRUG3',
 'DRUG4',
 'DRUG5',
 'DRUG6',
 'DRUG7',
 'DRUG8',
 'DRUG9',
 'DRUG10',
 'DRUG11',
 'DRUG12',
 'DRUG13',
 'DRUG14',
 'DRUG15',
 'DRUG16',
 'DRUG17',
 'DRUG18',
 'DRUG19',
 'DRUG20',
 'DRUG21',
 'DRUG22',
 'DRUG23',
 'DRUG24',
 'DRUG25',
 'DRUG26',
 'DRUG27',
 'DRUG28',
 'DRUG29',
 'DRUG30',
 'DRUG31',
 'DRUG32',
 'DRUG33',
 'DRUG34',
 'DRUG35',
 'DRUG36',
 'DRUG37',
 'DRUG38',
 'DRUG39',
 'DRUG40',
 'TOBAC30',


In [12]:
np.where(np.array(data_store_title)=='CDRGLOB')

(array([218]),)

In [13]:
output_path="./data/survival_data_filtered_1_VisitCount.csv"
title=np.array(data_store_title)
write_to_csv(title.reshape(1,title.shape[0]),output_path)

write_to_csv(data_store_,output_path)

In [14]:
data_store_.shape

(304, 839)

In [15]:
NPPATHO_index=np.where(title=='NPPATHO')[0][0]

# DRUG

In [16]:
str_DRUG='DRUG'
list_DRUG=[]
for i in np.arange(1,41,1):
    list_DRUG.append(str_DRUG+str(i))

#----------------------------------------------------------------
DRUG_index_list=[]
for list_DRUG_i in list_DRUG:
    DRUG_index_list.append(np.where(title==list_DRUG_i)[0][0])
    
#----------------------------------------------------------------
data_store_arr=np.array(data_store_)

DRUG_data=data_store_arr[:,np.array(DRUG_index_list)]
DRUG_data_fill=np.array(pd.DataFrame(DRUG_data).fillna("-1"))

#----------------------------------------------------------------
Dict_DRUG_data_fill={}
DRUG_data_fill_unique=np.unique(DRUG_data_fill)

DRUG_data_fill_unique_drop_neg1_index=np.where(DRUG_data_fill_unique!='-1')[0]
Dict_DRUG_data_fill["-1"]=-1

DRUG_data_fill_unique_drop_neg1=DRUG_data_fill_unique[DRUG_data_fill_unique_drop_neg1_index]

for DRUG_data_fill_index_i in np.arange(len(DRUG_data_fill_unique_drop_neg1)):
    DRUG_data_fill_i=DRUG_data_fill_unique_drop_neg1[DRUG_data_fill_index_i]
    Dict_DRUG_data_fill[DRUG_data_fill_i]=DRUG_data_fill_index_i

In [17]:
Dict_DRUG_data_fill

{'-1': -1,
 'ACETAMINOPHEN': 0,
 'ACETAMINOPHEN-CHLORPHENIRAMINE': 1,
 'ACETAMINOPHEN-HYDROCODONE': 2,
 'ACETAZOLAMIDE': 3,
 'ACETYL-L-CARNITINE': 4,
 'ACYCLOVIR': 5,
 'AL HYDROXIDE/MG HYDROXIDE/SIMETHICONE': 6,
 'ALBUTEROL': 7,
 'ALBUTEROL-IPRATROPIUM': 8,
 'ALENDRONATE': 9,
 'ALLOPURINOL': 10,
 'ALPHA LIPOIC ACID': 11,
 'ALPHA-LIPOIC ACID': 12,
 'ALPRAZOLAM': 13,
 'ALUMINUM HYDROXIDE-MAGNESIUM HYDROXIDE': 14,
 'AMANTADINE': 15,
 'AMITRIPTYLINE': 16,
 'AMLODIPINE': 17,
 'AMLODIPINE-VALSARTAN': 18,
 'AMOXAPINE': 19,
 'APIXABAN': 20,
 'ARIPIPRAZOLE': 21,
 'ASCORBIC ACID': 22,
 'ASPIRIN': 23,
 'ASPIRIN-DIPYRIDAMOLE': 24,
 'ATENOLOL': 25,
 'ATENOLOL-CHLORTHALIDONE': 26,
 'ATORVASTATIN': 27,
 'ATROPINE': 28,
 'ATROPINE-DIPHENOXYLATE': 29,
 'AZITHROMYCIN': 30,
 'BACLOFEN': 31,
 'BENAZEPRIL': 32,
 'BETAMETHASONE-CLOTRIMAZOLE TOPICAL': 33,
 'BETHANECHOL': 34,
 'BICALUTAMIDE': 35,
 'BIFIDOBACTERIUM-LACTOBACILLUS': 36,
 'BIMATOPROST OPHTHALMIC': 37,
 'BIOTIN': 38,
 'BISACODYL': 39,
 'BISMUTH SU

In [18]:
for i in np.arange(DRUG_data_fill.shape[0]):
    for j in np.arange(DRUG_data_fill.shape[1]):
        DRUG_data_fill_i_j=DRUG_data_fill[i,j]
        data_store_arr[i,DRUG_index_list[0]+j]=Dict_DRUG_data_fill[DRUG_data_fill_i_j]

In [19]:
data_store_arr

array([[4, 2, 2, ..., 33, 1346, True],
       [1, 1, 2, ..., 2, 0, False],
       [1, 2, 1, ..., 95, 0, False],
       ...,
       [10, 2, 2, ..., 3, 1098, True],
       [1, 7, 2, ..., 12, 0, False],
       [5, 1, 2, ..., 43, 759, True]], dtype=object)

# NACCWRI

In [20]:
list_NACCWRI=['NACCWRI1','NACCWRI2','NACCWRI3']

#----------------------------------------------------------------
NACCWRI_index_list=[]
for list_NACCWRI_i in list_NACCWRI:
    NACCWRI_index_list.append(np.where(title==list_NACCWRI_i)[0][0])

In [21]:
NACCWRI_index_list

[825, 826, 827]

In [22]:
#----------------------------------------------------------------
NACCWRI_data=data_store_arr[:,np.array(NACCWRI_index_list)]
NACCWRI_data_fill=np.array(pd.DataFrame(NACCWRI_data).fillna("-1"))

In [23]:
#----------------------------------------------------------------
Dict_NACCWRI_data_fill={}
NACCWRI_data_fill_unique=np.unique(NACCWRI_data_fill)

NACCWRI_data_fill_unique_drop_neg1_index=np.where(NACCWRI_data_fill_unique!='-1')[0]
Dict_NACCWRI_data_fill["-1"]=-1

NACCWRI_data_fill_unique_drop_neg1=NACCWRI_data_fill_unique[NACCWRI_data_fill_unique_drop_neg1_index]

for NACCWRI_data_fill_index_i in np.arange(len(NACCWRI_data_fill_unique_drop_neg1)):
    NACCWRI_data_fill_i=NACCWRI_data_fill_unique_drop_neg1[NACCWRI_data_fill_index_i]
    Dict_NACCWRI_data_fill[NACCWRI_data_fill_i]=NACCWRI_data_fill_index_i

In [24]:
for i in np.arange(NACCWRI_data_fill.shape[0]):
    for j in np.arange(NACCWRI_data_fill.shape[1]):
        NACCWRI_data_fill_i_j=NACCWRI_data_fill[i,j]
        data_store_arr[i,NACCWRI_index_list[0]+j]=Dict_NACCWRI_data_fill[NACCWRI_data_fill_i_j]

In [25]:
data_store_arr

array([[4, 2, 2, ..., 33, 1346, True],
       [1, 1, 2, ..., 2, 0, False],
       [1, 2, 1, ..., 95, 0, False],
       ...,
       [10, 2, 2, ..., 3, 1098, True],
       [1, 7, 2, ..., 12, 0, False],
       [5, 1, 2, ..., 43, 759, True]], dtype=object)

In [26]:
data_store_arr.shape

(304, 839)

In [27]:
data_store_arr[:,NPPATHO_index]=np.array(pd.DataFrame(data_store_arr[:,NPPATHO_index]).fillna(-1))[:,0]

In [28]:
data_store_arr[:,NPPATHO_index]

array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, -1.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,

In [29]:
output_path="./data/survival_data_filtered_2_VisitCount.csv"
title=np.array(data_store_title)
write_to_csv(title.reshape(1,title.shape[0]),output_path)

write_to_csv(data_store_arr,output_path)